# Generated by Django 3.1.1 on 2020-10-22 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBFapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 22, 16, 19, 47, 598519), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 22, 15, 19, 47, 598519), verbose_name='Start Time'),
        ),
    ]
