# Generated by Django 3.1.1 on 2020-10-23 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBFapp', '0002_auto_20201022_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.date(2020, 10, 23), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 23, 14, 25, 10, 720193), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 23, 13, 25, 10, 720193), verbose_name='Start Time'),
        ),
    ]
