# Generated by Django 3.1.1 on 2020-10-23 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SBFapp', '0003_auto_20201023_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 23, 17, 26, 23, 685392, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 23, 17, 26, 23, 572367, tzinfo=utc), verbose_name='Start Time'),
        ),
    ]
