# Generated by Django 3.1.1 on 2020-11-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBFapp', '0011_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='days',
            field=models.ManyToManyField(to='SBFapp.Recurrence'),
        ),
    ]
