# Generated by Django 3.1.1 on 2020-11-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBFapp', '0013_auto_20201106_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='choice',
            field=models.CharField(choices=[('Monday', '1'), ('Tuesday', '2'), ('Wednesday', '3'), ('Thursday', '4'), ('Friday', '5'), ('Saturday', '6'), ('Sunday', '7')], max_length=10, unique=True),
        ),
    ]
