# Generated by Django 3.1.1 on 2020-11-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBFapp', '0015_auto_20201108_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('help', 'Help Request'), ('find', 'Buddy Finder')], default='', max_length=20),
        ),
    ]
