# Generated by Django 3.1.2 on 2020-11-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SBFapp', '0017_auto_20201111_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SBFapp.post'),
            preserve_default=False,
        ),
    ]
