# Generated by Django 3.1.2 on 2020-11-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBFapp', '0019_auto_20201112_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
