# Generated by Django 3.1.2 on 2020-11-22 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SBFapp', '0023_auto_20201122_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='list_users',
            field=models.ManyToManyField(related_name='group_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
