# Generated by Django 3.1.2 on 2020-11-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBFapp', '0025_auto_20201122_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='private',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
