# Generated by Django 3.1.2 on 2020-11-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBFapp', '0021_auto_20201119_0019'),
        ('SBFapp', '0026_group_private'),
    ]

    operations = [
    ]
