# Generated by Django 3.1.2 on 2020-11-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBFapp', '0027_merge_20201122_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='room',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
